name: Check idc releases and update index accordingly
on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 */1 * *

jobs:
  update_idc_index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install requests==2.31.0 pandas==2.1.1 google-cloud-bigquery==3.12.0 pyarrow==13.0.0  db-dtypes==1.1.1 PyGithub==2.1.1
    
    - name: Authorize Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        create_credentials_file: true
        export_environment_variables: true    
  
    - name: Run script to get the latest idc release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/get-latest-index.py
