name: keep-github-actions-alive

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "keep-alive"
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          time_elapsed: 50
